version: "3"
services:
  game:
    build: 
      context: ./game
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - app_network
    restart: always
  cms:
    build: 
      context: ./cms
      dockerfile: ./Dockerfile
    volumes:
      - ./cms/database:/cms/database:rw
      - ./cms/public/uploads:/cms/public/uploads:rw
    ports:
      - 1337:1337
    networks:
      - app_network
    restart: always
  lucky-draw:
    build: 
      context: ./lucky-draw
      dockerfile: ./Dockerfile
    networks:
      - app_network
    restart: always
  mysql:
    image: mysql:8.0.35
    command: --default-authentication-plugin=mysql_native_password --max_connections=1000
    environment:
      MYSQL_DATABASE: ismart-arena
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql:rw
    ports:
      - 3306:3306
    networks:
      - app_network
    restart: always
networks:
  app_network:
    driver: bridge